dependencies:
  - pip
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader
  - bokeh::bokeh=1.1.0
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::geoviews-core
  - pyviz/label/dev::panel
  - conda-forge::hvplot
  - conda-forge::scrapy
  - conda-forge::requests
  - conda-forge::pandas
  - conda-forge::time
  - conda-forge::selenium
  - conda-forge::lxml
  - conda-forge::cartopy
  - conda-forge::geoviews
  - conda-forge::xlrd
  - pip:
    - jupyter-panel-proxy
